name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7',  '3.8', '3.9', '3.10', '3.11', 'pypy3.8', 'pypy3.9']
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: $${ matrix.python-version }
          cache: pip
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          python -m pip -r requirements.txt
      - name: Run tests for ${{ matrix.python-version }}
        run:
          python -m pytest -vv